services:
   namenode:
      image: apache/hadoop:3
      hostname: namenode
      volumes:
        - ./Makefile:/opt/hadoop/Makefile
        - ./WC:/opt/hadoop/WC
      command: ["hdfs", "namenode"]
      ports:
        - 9870:9870
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
   datanode:
      image: apache/hadoop:3
      command: ["hdfs", "datanode"]
      env_file:
        - ./config       
   resourcemanager:
      image: apache/hadoop:3
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - ./config
   nodemanager:
      image: apache/hadoop:3
      command: ["yarn", "nodemanager"]
      env_file:
        - ./config

   spark-master:
      image: blnkoff/spark-master:latest
      container_name: spark-master
      hostname: spark-master
      volumes:
        - ./Makefile:/opt/spark-apps
      environment:
        - SPARK_MODE=master
        - SPARK_MASTER_HOST=spark-master
        - SPARK_MASTER_PORT=7077
        - SPARK_UI_PORT=8080
      ports:
        - 8080:8080  
        - 7077:7077 
      depends_on:
        - resourcemanager
        - namenode

   spark-worker:
      image: blnkoff/spark-worker:latest
      container_name: spark-worker
      hostname: spark-worker
      environment:
        - SPARK_MODE=worker
        - SPARK_MASTER_URL=spark://spark-master:7077
        # - SPARK_WORKER_MEMORY=2g
        # - SPARK_WORKER_CORES=2
      depends_on:
        - spark-master
        - nodemanager